name: Publish to npm and GitHub Packages

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # For GitHub Packages

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Build the package and create a tarball
      - name: Install and Pack
        run: |
          npm ci
          npm pack  # Creates orange_icons-1.1.22.tgz

      # Publish to npm (unscoped)
      - name: Publish to npm
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
      - run: |
          cp capybaraicons-orange_icons-*.tgz orange_icons-*.tgz
          npm publish orange_icons-*.tgz --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Publish to GitHub Packages (scoped)
      - name: Publish to GitHub Packages
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"
          scope: "@capybaraicons" # Link scope to GitHub's registry
      - run: npm publish capybaraicons-orange_icons-*.tgz --workspace=false
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
